export type CardType =
  | "Faction"
  | "Group"
  | "Plot"
  | "Resource"
  | "New World Order"
  | "Personality"
  | "Place"
  | "Organization"
  | "Special"
  | "Goal"
  | "Artifact"
  | "Disaster"

export interface BaseCard {
  id: string
  name: string
  type: CardType
  imageUrl: string
  description: string
  isUnique?: boolean
}

export interface FactionCard extends BaseCard {
  type: "Faction"
  rarity: string
  power: string // e.g., "7/7"
  specialGoal: string
  abilities: string[] // Array of abilities/rules text
}

export interface GroupLikeCard extends BaseCard {
  type: "Group" | "Resource" | "Place" | "Personality" | "Organization" | "Artifact"
  power: number
  resistance: number
  income: number
  alignments: string[] // e.g., ["Government", "Violent"]
}

export interface EventLikeCard extends BaseCard {
  type: "Plot" | "Special" | "Goal" | "Disaster" | "New World Order"
  // These typically don't have power/resistance/income
}

// Centralized card data
export const cards: (FactionCard | GroupLikeCard | EventLikeCard)[] = [
  // Existing Faction Cards (now Faction type)
  {
    id: "adepts-of-hermes",
    name: "Adepts of Hermes",
    type: "Faction",
    rarity: "I",
    imageUrl: "/cards/adepts-of-hermes.webp",
    power: "7/7",
    specialGoal: "Each Magic Resource you control counts as one group toward the Basic Goal.",
    abilities: [
      "If you fail an Attack to Control against a Group from your own hand, you do not lose the group . . . just return the card to your hand.",
      "The Adepts of Hermes have a +6 on any attempt to control or destroy a Magic group.",
    ],
    description:
      "Masters of ancient wisdom and occult knowledge, seeking to guide humanity through esoteric enlightenment.",
  },
  {
    id: "bavarian-illuminati",
    name: "Bavarian Illuminati",
    type: "Faction",
    rarity: "I",
    imageUrl: "/cards/bavarian-illuminati.webp",
    power: "10/10",
    specialGoal: "Control a total Power of 50 or more, counting Bavaria's own Power.",
    abilities: ["Each turn, you may declare one of your attacks privileged."],
    description: "The classic conspiracy masterminds, pulling strings from the shadows to reshape the world order.",
  },
  {
    id: "bermuda-triangle",
    name: "Bermuda Triangle",
    type: "Faction",
    rarity: "I",
    imageUrl: "/cards/bermuda-triangle.webp",
    power: "8/8",
    specialGoal:
      "Control a total Power of at least 35, counting Bermuda's own Power, and at least one group of each alignment. A group with more than one alignment counts for all its alignments.",
    abilities: ["You may reorganize your groups freely at the end of your turn."],
    description: "Mysterious forces from the depths, wielding otherworldly powers and unexplained phenomena.",
  },
  {
    id: "discordian-society",
    name: "Discordian Society",
    type: "Faction",
    rarity: "I",
    imageUrl: "/cards/discordian-society.webp",
    power: "7/7",
    specialGoal:
      "Any Weird group with a Power of 3 or more counts double toward your total number of groups controlled.",
    abilities: [
      "You have a +4 on any attempt to control Weird groups.",
      "Your power structure is immune to attacks from Government or Straight groups, and to all special abilities of these groups.",
    ],
    description: "Agents of chaos and confusion, spreading discord to disrupt established power structures.",
  },
  {
    id: "gnomes-of-zurich",
    name: "Gnomes of Zürich",
    type: "Faction",
    rarity: "I",
    imageUrl: "/cards/gnomes-of-zurich.png",
    power: "9/9",
    specialGoal:
      "Any Corporate group or Bank with a Power of 4 or more counts double toward your total number of groups controlled.",
    abilities: [
      "You may hold 6 Plot cards in your hand, rather than the usual 5.",
      "You have a +4 on any attempt to control any Bank.",
    ],
    description: "Financial puppet masters controlling global economics through banking and monetary manipulation.",
  },
  {
    id: "the-network",
    name: "The Network",
    type: "Faction",
    rarity: "I",
    imageUrl: "/cards/the-network.webp",
    power: "8/8",
    specialGoal:
      "Any Computer group with a Power of 3 or more counts double toward your total number of groups controlled.",
    abilities: ["You start your turn by drawing two Plot cards, rather than one."],
    description: "Information brokers and media manipulators, controlling the flow of knowledge and public opinion.",
  },
  {
    id: "servants-of-cthulhu",
    name: "Servants of Cthulhu",
    type: "Faction",
    rarity: "I",
    imageUrl: "/cards/servants-of-cthulhu.webp",
    power: "9/9",
    specialGoal:
      "For every group you destroy, reduce by 1 the number of groups you need to control in order to win. You may also count rival Illuminati which you destroy by removing their last group. If you destroy 8 groups, you win, regardless of how many you control!",
    abilities: [
      "You have a +4 on any attempt to destroy, even with Disasters and Assassinations.",
      "Draw a Plot card whenever you destroy a group!",
    ],
    description: "Cultists serving ancient cosmic horrors, seeking to bring about the end of human civilization.",
  },
  {
    id: "shangri-la",
    name: "Shangri-La",
    type: "Faction",
    rarity: "I",
    imageUrl: "/cards/shangri-la.webp",
    power: "7/7",
    specialGoal:
      "Have Peaceful groups with a total Power of 30 in play, regardless of who controls them! If this happens, all Shangri-La players share the victory.",
    abilities: [
      "Any group in your Power Structure has an extra +5 to defend against any attack, even Instants.",
      "You cannot destroy any groups except Violent ones and rival Illuminati.",
    ],
    description: "Peaceful isolationists from hidden mountain sanctuaries, promoting harmony and spiritual balance.",
  },
  {
    id: "ufos",
    name: "UFOs",
    type: "Faction",
    rarity: "I",
    imageUrl: "/cards/ufos.webp",
    power: "6/6",
    specialGoal: "The UFOs can have up to 3 different Goal cards in play, and win with any of them.",
    abilities: [
      "The UFOs have two actions per turn — they get two tokens!",
      "These may not be used in the same attack.",
    ],
    description: "Extraterrestrial visitors with advanced technology and mysterious agendas for Earth.",
  },
  {
    id: "society-of-assassins",
    name: "Society of Assassins",
    type: "Faction",
    rarity: "I",
    imageUrl: "/cards/society-of-assassins.webp",
    power: "7/7",
    specialGoal:
      "Any Secret group counts double for you as long as none of your rivals control a Secret group with more power.",
    abilities: [
      "When one of your Fanatic groups attacks or defends, you may treat its Fanatic alignment as the same as that of any other Fanatic group.",
      "Your Fanatic groups also have Global Power equal to their Power.",
    ],
    description: "Elite killers and shadow operatives, eliminating obstacles through precision and stealth.",
  },
  {
    id: "church-of-the-subgenius",
    name: "Church of the SubGenius",
    type: "Faction",
    rarity: "I",
    imageUrl: "/cards/church-of-the-subgenius.webp",
    power: "7/7",
    specialGoal:
      "Up to three Slack (Illuminati) tokens on the Church of the SubGenius may count as groups toward your Basic Goal. This Goal cannot be combined with any other Goal.",
    abilities: [
      "The Church of the SubGenius may accumulate its Action tokens ('Slack') each turn, though it can spend only one per action.",
      "It, and any SubGenius groups in its Power Structure, has +2 for direct control of any SubGenius group.",
    ],
    description: "Satirical pseudo-religious movement promoting slack and absurdist philosophy.",
  },
  // New Group Cards
  {
    id: "cia",
    name: "CIA",
    type: "Group",
    imageUrl: "/placeholder-qb36r.png",
    description: "The Central Intelligence Agency. A powerful government group.",
    power: 7,
    resistance: 6,
    income: 5,
    alignments: ["Government", "Violent"],
  },
  {
    id: "pentagon",
    name: "The Pentagon",
    type: "Group",
    imageUrl: "/pentagon-group-card.png",
    description: "The headquarters of the U.S. Department of Defense.",
    power: 8,
    resistance: 7,
    income: 6,
    alignments: ["Government", "Violent"],
  },
  {
    id: "hollywood",
    name: "Hollywood",
    type: "Group",
    imageUrl: "/hollywood-group-card.png",
    description: "The dream factory, controlling minds through entertainment.",
    power: 4,
    resistance: 3,
    income: 4,
    alignments: ["Media", "Fanatic"],
  },
  {
    id: "big-media",
    name: "Big Media",
    type: "Group",
    imageUrl: "/placeholder-666u8.png",
    description: "The corporate giants shaping public opinion.",
    power: 6,
    resistance: 5,
    income: 7,
    alignments: ["Corporate", "Media"],
  },
  {
    id: "kfc",
    name: "KFC",
    type: "Group",
    imageUrl: "/fried-chicken-group-card.png",
    description: "Finger lickin' good . . . and mind control.",
    power: 3,
    resistance: 2,
    income: 3,
    alignments: ["Corporate"],
  },
  {
    id: "united-nations",
    name: "United Nations",
    type: "Group",
    imageUrl: "/placeholder-kgss7.png",
    description: "A global organization with hidden agendas.",
    power: 7,
    resistance: 7,
    income: 6,
    alignments: ["Government", "Peaceful"],
  },
  {
    id: "men-in-black",
    name: "Men in Black",
    type: "Group",
    imageUrl: "/men-in-black-group.png",
    description: "Mysterious agents suppressing paranormal knowledge.",
    power: 5,
    resistance: 7,
    income: 4,
    alignments: ["Secret", "Government"],
  },
  {
    id: "nasa",
    name: "NASA",
    type: "Group",
    imageUrl: "/nasa-group-card.png",
    description: "Exploring space, or hiding alien secrets?",
    power: 6,
    resistance: 5,
    income: 5,
    alignments: ["Government", "Science"],
  },
  {
    id: "boy-scouts",
    name: "Boy Scouts",
    type: "Group",
    imageUrl: "/boy-scouts-group-card.png",
    description: "Innocent youth, or future operatives?",
    power: 2,
    resistance: 1,
    income: 1,
    alignments: ["Peaceful"],
  },
  {
    id: "smash-tv",
    name: "Smash TV",
    type: "Group",
    imageUrl: "/smash-tv-group-card.png",
    description: "A violent game show that controls the masses.",
    power: 5,
    resistance: 4,
    income: 3,
    alignments: ["Media", "Violent"],
  },
  {
    id: "the-network-group",
    name: "The Network (Group)",
    type: "Group",
    imageUrl: "/placeholder-f3io0.png",
    description: "A vast web of interconnected individuals and systems.",
    power: 6,
    resistance: 6,
    income: 5,
    alignments: ["Computer", "Secret"],
  },
  {
    id: "the-phone-company",
    name: "The Phone Company",
    type: "Group",
    imageUrl: "/phone-company-group-card.png",
    description: "Listening in on every conversation.",
    power: 5,
    resistance: 4,
    income: 6,
    alignments: ["Corporate", "Computer"],
  },
  {
    id: "the-subgenius-group",
    name: "The SubGenius (Group)",
    type: "Group",
    imageUrl: "/subgenius-group-card.png",
    description: "Followers of J.R. 'Bob' Dobbs.",
    power: 3,
    resistance: 2,
    income: 2,
    alignments: ["Weird"],
  },
  {
    id: "the-internet",
    name: "The Internet",
    type: "Group",
    imageUrl: "/internet-group-card.png",
    description: "The ultimate network for information and misinformation.",
    power: 9,
    resistance: 8,
    income: 8,
    alignments: ["Computer", "Media"],
  },
  {
    id: "the-illuminati-university",
    name: "The Illuminati University",
    type: "Group",
    imageUrl: "/placeholder-4n9z0.png",
    description: "Where future conspirators are trained.",
    power: 4,
    resistance: 3,
    income: 3,
    alignments: ["Academic", "Secret"],
  },
  {
    id: "the-vatican",
    name: "The Vatican",
    type: "Group",
    imageUrl: "/vatican-group-card.png",
    description: "Ancient power, hidden influence.",
    power: 7,
    resistance: 7,
    income: 5,
    alignments: ["Religious"],
  },
  {
    id: "the-trilateral-commission",
    name: "The Trilateral Commission",
    type: "Group",
    imageUrl: "/trilateral-commission-card.png",
    description: "Elite globalists pulling the strings.",
    power: 8,
    resistance: 7,
    income: 7,
    alignments: ["Corporate", "Government", "Secret"],
  },
  {
    id: "the-mafia",
    name: "The Mafia",
    type: "Group",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Organized crime, disorganized world.",
    power: 6,
    resistance: 5,
    income: 4,
    alignments: ["Criminal", "Violent"],
  },
  {
    id: "the-boy-bands",
    name: "The Boy Bands",
    type: "Group",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Controlling teenage minds with catchy tunes.",
    power: 2,
    resistance: 1,
    income: 2,
    alignments: ["Media"],
  },
  {
    id: "the-gnostic-mass",
    name: "The Gnostic Mass",
    type: "Group",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Ancient rituals for modern control.",
    power: 4,
    resistance: 3,
    income: 2,
    alignments: ["Magic", "Religious"],
  },
  {
    id: "the-l-a-riots",
    name: "The L.A. Riots",
    type: "Group",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Chaos on the streets, opportunity for the powerful.",
    power: 6,
    resistance: 0,
    income: 0,
    alignments: ["Violent", "Weird"],
  },
  {
    id: "the-simpsons",
    name: "The Simpsons",
    type: "Group",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Predicting the future, or causing it?",
    power: 3,
    resistance: 2,
    income: 3,
    alignments: ["Media"],
  },
  {
    id: "the-new-mexico-state-police",
    name: "The New Mexico State Police",
    type: "Group",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Keeping order in the land of enchantment.",
    power: 4,
    resistance: 3,
    income: 2,
    alignments: ["Government"],
  },
  {
    id: "the-bermuda-triangle-group",
    name: "The Bermuda Triangle (Group)",
    type: "Group",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Mysterious disappearances and unexplained phenomena.",
    power: 5,
    resistance: 5,
    income: 3,
    alignments: ["Weird", "Magic"],
  },
  {
    id: "the-gnomes-of-zurich-group",
    name: "The Gnomes of Zürich (Group)",
    type: "Group",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Secretive bankers controlling global finance.",
    power: 8,
    resistance: 7,
    income: 9,
    alignments: ["Corporate", "Secret"],
  },
  {
    id: "the-servants-of-cthulhu-group",
    name: "The Servants of Cthulhu (Group)",
    type: "Group",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Cultists preparing for the awakening of the Great Old Ones.",
    power: 7,
    resistance: 6,
    income: 4,
    alignments: ["Fanatic", "Magic"],
  },
  {
    id: "the-shangri-la-group",
    name: "The Shangri-La (Group)",
    type: "Group",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "A hidden paradise, or a secret base?",
    power: 6,
    resistance: 8,
    income: 5,
    alignments: ["Peaceful", "Secret"],
  },
  {
    id: "the-ufos-group",
    name: "The UFOs (Group)",
    type: "Group",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Unidentified flying objects, watching us all.",
    power: 5,
    resistance: 6,
    income: 3,
    alignments: ["Weird", "Science"],
  },
  {
    id: "the-society-of-assassins-group",
    name: "The Society of Assassins (Group)",
    type: "Group",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Silent killers, precise strikes.",
    power: 7,
    resistance: 5,
    income: 4,
    alignments: ["Criminal", "Violent", "Secret"],
  },
  {
    id: "the-church-of-the-subgenius-group",
    name: "The Church of the SubGenius (Group)",
    type: "Group",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Praise 'Bob'!",
    power: 4,
    resistance: 3,
    income: 3,
    alignments: ["Weird", "Religious"],
  },
  // New Plot Cards
  {
    id: "subliminal-messages",
    name: "Subliminal Messages",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Influence the masses without them knowing.",
  },
  {
    id: "assassination-plot",
    name: "Assassination",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Eliminate a key player.",
  },
  {
    id: "back-to-the-salt-mines",
    name: "Back to the Salt Mines",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Force a rival to discard cards.",
  },
  {
    id: "computer-virus",
    name: "Computer Virus",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Disrupt a rival's network.",
  },
  {
    id: "media-blitz",
    name: "Media Blitz",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Control the narrative with overwhelming propaganda.",
  },
  {
    id: "bribery",
    name: "Bribery",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Persuade a group to join your cause.",
  },
  {
    id: "disaster-plot",
    name: "Disaster",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Unleash a catastrophe upon your enemies.",
  },
  {
    id: "economic-sanctions",
    name: "Economic Sanctions",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Crippling a rival's income.",
  },
  {
    id: "false-flag",
    name: "False Flag",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Blame your enemies for your own actions.",
  },
  {
    id: "mind-control",
    name: "Mind Control",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Take direct control of a personality.",
  },
  {
    id: "propaganda",
    name: "Propaganda",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Shape public opinion to your will.",
  },
  {
    id: "secret-meeting",
    name: "Secret Meeting",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Conspire in the shadows.",
  },
  {
    id: "stock-market-crash",
    name: "Stock Market Crash",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Plunge the world into financial chaos.",
  },
  {
    id: "terrorist-attack",
    name: "Terrorist Attack",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Unleash fear and disorder.",
  },
  {
    id: "weather-control",
    name: "Weather Control",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Manipulate the elements for your gain.",
  },
  {
    id: "alien-invasion",
    name: "Alien Invasion",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "A global threat, or a convenient distraction?",
  },
  {
    id: "global-warming",
    name: "Global Warming",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "A slow-burning disaster.",
  },
  {
    id: "vaccine-mandate",
    name: "Vaccine Mandate",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Control through public health.",
  },
  {
    id: "deep-state-leak",
    name: "Deep State Leak",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Expose a rival's secrets.",
  },
  {
    id: "cyber-attack",
    name: "Cyber Attack",
    type: "Plot",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Bring down the digital infrastructure.",
  },
  // New Special Cards
  {
    id: "assassination-special",
    name: "Assassination",
    type: "Special",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Eliminate a key player.",
  },
  {
    id: "back-to-the-salt-mines-special",
    name: "Back to the Salt Mines",
    type: "Special",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Force a rival to discard cards.",
  },
  {
    id: "computer-virus-special",
    name: "Computer Virus",
    type: "Special",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Disrupt a rival's network.",
  },
  {
    id: "media-blitz-special",
    name: "Media Blitz",
    type: "Special",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Control the narrative with overwhelming propaganda.",
  },
  {
    id: "bribery-special",
    name: "Bribery",
    type: "Special",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Persuade a group to join your cause.",
  },
  {
    id: "disaster-special",
    name: "Disaster",
    type: "Special",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Unleash a catastrophe upon your enemies.",
  },
  {
    id: "economic-sanctions-special",
    name: "Economic Sanctions",
    type: "Special",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Crippling a rival's income.",
  },
  {
    id: "false-flag-special",
    name: "False Flag",
    type: "Special",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Blame your enemies for your own actions.",
  },
  {
    id: "mind-control-special",
    name: "Mind Control",
    type: "Special",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Take direct control of a personality.",
  },
  {
    id: "propaganda-special",
    name: "Propaganda",
    type: "Special",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Shape public opinion to your will.",
  },
  {
    id: "secret-meeting-special",
    name: "Secret Meeting",
    type: "Special",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Conspire in the shadows.",
  },
  {
    id: "stock-market-crash-special",
    name: "Stock Market Crash",
    type: "Special",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Plunge the world into financial chaos.",
  },
  {
    id: "terrorist-attack-special",
    name: "Terrorist Attack",
    type: "Special",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Unleash fear and disorder.",
  },
  {
    id: "weather-control-special",
    name: "Weather Control",
    type: "Special",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Manipulate the elements for your gain.",
  },
  {
    id: "alien-invasion-special",
    name: "Alien Invasion",
    type: "Special",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "A global threat, or a convenient distraction?",
  },
  {
    id: "global-warming-special",
    name: "Global Warming",
    type: "Special",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "A slow-burning disaster.",
  },
  {
    id: "vaccine-mandate-special",
    name: "Vaccine Mandate",
    type: "Special",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Control through public health.",
  },
  {
    id: "deep-state-leak-special",
    name: "Deep State Leak",
    type: "Special",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Expose a rival's secrets.",
  },
  {
    id: "cyber-attack-special",
    name: "Cyber Attack",
    type: "Special",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Bring down the digital infrastructure.",
  },
  // New Goal Cards
  {
    id: "world-domination",
    name: "World Domination",
    type: "Goal",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Control 10 groups.",
  },
  {
    id: "financial-control",
    name: "Financial Control",
    type: "Goal",
    type: "Goal",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Accumulate 50 income.",
  },
  {
    id: "media-mastery",
    name: "Media Mastery",
    type: "Goal",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Control all Media groups.",
  },
  {
    id: "global-peace",
    name: "Global Peace",
    type: "Goal",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Have no Violent groups in play.",
  },
  {
    id: "technological-singularity",
    name: "Technological Singularity",
    type: "Goal",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Control all Computer groups.",
  },
  // New Resource Cards
  {
    id: "computer-resource",
    name: "Computer",
    type: "Resource",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Provides a bonus to Computer groups.",
    power: 0,
    resistance: 0,
    income: 1,
    alignments: ["Computer"],
  },
  {
    id: "magic-resource",
    name: "Magic",
    type: "Resource",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Provides a bonus to Magic groups.",
    power: 0,
    resistance: 0,
    income: 1,
    alignments: ["Magic"],
  },
  {
    id: "money-resource",
    name: "Money",
    type: "Resource",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Provides extra income.",
    power: 0,
    resistance: 0,
    income: 2,
    alignments: ["Corporate"],
  },
  {
    id: "weapons-resource",
    name: "Weapons",
    type: "Resource",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Provides a bonus to Violent groups.",
    power: 0,
    resistance: 0,
    income: 0,
    alignments: ["Violent"],
  },
  {
    id: "information-resource",
    name: "Information",
    type: "Resource",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Provides a bonus to Media groups.",
    power: 0,
    resistance: 0,
    income: 1,
    alignments: ["Media"],
  },
  // New Place Cards
  {
    id: "area-51",
    name: "Area 51",
    type: "Place",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "A mysterious government facility.",
    power: 0,
    resistance: 0,
    income: 0,
    alignments: ["Secret", "Government"],
  },
  {
    id: "stonehenge",
    name: "Stonehenge",
    type: "Place",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "An ancient monument with mystical properties.",
    power: 0,
    resistance: 0,
    income: 0,
    alignments: ["Magic", "Peaceful"],
  },
  {
    id: "the-white-house",
    name: "The White House",
    type: "Place",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "The seat of U.S. power.",
    power: 0,
    resistance: 0,
    income: 0,
    alignments: ["Government"],
  },
  {
    id: "wall-street",
    name: "Wall Street",
    type: "Place",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "The heart of global finance.",
    power: 0,
    resistance: 0,
    income: 0,
    alignments: ["Corporate"],
  },
  {
    id: "hollywood-place",
    name: "Hollywood",
    type: "Place",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "The dream factory.",
    power: 0,
    resistance: 0,
    income: 0,
    alignments: ["Media"],
  },
  // New Personality Cards
  {
    id: "bill-gates",
    name: "Bill Gates",
    type: "Personality",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "A powerful figure in the tech world.",
    power: 5,
    resistance: 4,
    income: 3,
    alignments: ["Corporate", "Computer"],
  },
  {
    id: "oprah-winfrey",
    name: "Oprah Winfrey",
    type: "Personality",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "A media mogul with immense influence.",
    power: 4,
    resistance: 3,
    income: 5,
    alignments: ["Media"],
  },
  {
    id: "the-pope",
    name: "The Pope",
    type: "Personality",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "The spiritual leader of billions.",
    power: 6,
    resistance: 5,
    income: 2,
    alignments: ["Religious"],
  },
  {
    id: "dalai-lama",
    name: "Dalai Lama",
    type: "Personality",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "A symbol of peace and spiritual guidance.",
    power: 3,
    resistance: 6,
    income: 1,
    alignments: ["Peaceful", "Religious"],
  },
  {
    id: "elon-musk",
    name: "Elon Musk",
    type: "Personality",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Visionary entrepreneur, or mad scientist?",
    power: 7,
    resistance: 5,
    income: 6,
    alignments: ["Corporate", "Science"],
  },
  // New Artifact Cards
  {
    id: "holy-grail",
    name: "Holy Grail",
    type: "Artifact",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "An ancient relic with mystical powers.",
    power: 0,
    resistance: 0,
    income: 0,
    alignments: ["Magic", "Religious"],
    isUnique: true,
  },
  {
    id: "ark-of-the-covenant",
    name: "Ark of the Covenant",
    type: "Artifact",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "A powerful biblical artifact.",
    power: 0,
    resistance: 0,
    income: 0,
    alignments: ["Magic", "Religious"],
    isUnique: true,
  },
  {
    id: "philosophers-stone",
    name: "Philosopher's Stone",
    type: "Artifact",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Grants immortality and turns lead into gold.",
    power: 0,
    resistance: 0,
    income: 0,
    alignments: ["Magic", "Science"],
    isUnique: true,
  },
  {
    id: "spear-of-destiny",
    name: "Spear of Destiny",
    type: "Artifact",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Whoever holds it controls the fate of the world.",
    power: 0,
    resistance: 0,
    income: 0,
    alignments: ["Violent", "Magic"],
    isUnique: true,
  },
  {
    id: "eye-of-providence",
    name: "Eye of Providence",
    type: "Artifact",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "The all-seeing eye, granting ultimate surveillance.",
    power: 0,
    resistance: 0,
    income: 0,
    alignments: ["Secret", "Magic"],
    isUnique: true,
  },
  // New Disaster Cards
  {
    id: "earthquake",
    name: "Earthquake",
    type: "Disaster",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Destroys a random group in play.",
  },
  {
    id: "meteor-strike",
    name: "Meteor Strike",
    type: "Disaster",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Destroys a specific group.",
  },
  {
    id: "financial-collapse",
    name: "Financial Collapse",
    type: "Disaster",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Reduces all players' income to zero for one turn.",
  },
  {
    id: "global-pandemic",
    name: "Global Pandemic",
    type: "Disaster",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Forces all players to discard cards.",
  },
  {
    id: "alien-abduction",
    name: "Alien Abduction",
    type: "Disaster",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Removes a personality from play.",
  },
  // New New World Order Cards
  {
    id: "new-world-order-card",
    name: "New World Order",
    type: "New World Order",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "Changes the rules of the game.",
  },
  {
    id: "age-of-enlightenment",
    name: "Age of Enlightenment",
    type: "New World Order",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "All Magic and Science groups gain +1 Power.",
  },
  {
    id: "total-surveillance",
    name: "Total Surveillance",
    type: "New World Order",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "All Secret groups gain +1 Income.",
  },
  {
    id: "corporate-takeover",
    name: "Corporate Takeover",
    type: "New World Order",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "All Corporate groups gain +1 Power and +1 Income.",
  },
  {
    id: "the-great-reset",
    name: "The Great Reset",
    type: "New World Order",
    imageUrl: "/placeholder.svg?height=300&width=200",
    description: "All players must discard their hand and draw 3 new cards.",
  },
]

// Update helper functions to use new interfaces
export function getCardById(id: string): FactionCard | GroupLikeCard | EventLikeCard | undefined {
  return cards.find((card) => card.id === id)
}

export function getFactionCards(): FactionCard[] {
  return cards.filter((card) => card.type === "Faction") as FactionCard[]
}

export function getGroupLikeCards(): GroupLikeCard[] {
  return cards.filter(
    (card) =>
      card.type === "Group" ||
      card.type === "Organization" ||
      card.type === "Personality" ||
      card.type === "Place" ||
      card.type === "Resource" ||
      card.type === "Artifact",
  ) as GroupLikeCard[]
}

export function getEventLikeCards(): EventLikeCard[] {
  return cards.filter(
    (card) =>
      card.type === "Plot" ||
      card.type === "Special" ||
      card.type === "Goal" ||
      card.type === "Disaster" ||
      card.type === "New World Order",
  ) as EventLikeCard[]
}
